name: Build and Deploy WriteWizard

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your repository
      - name: Check out code
        uses: actions/checkout@v3

      # 2) Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 3) Build and push the backend image
      - name: Build and push backend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/writewizard-backend:latest ./BackEnd
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/writewizard-backend:latest

      # 4) Build and push the frontend image
      - name: Build and push frontend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/writewizard-frontend:latest ./FrontEnd
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/writewizard-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: azureuser
          key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}
          script: |
            # Navigate to the directory containing your docker-compose.yml
            cd /home/azureuser
            # Pull the latest images
            docker-compose pull
            # Re-create or restart the containers
            docker-compose up -d
